import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

function read(path) {
  return readFileSync(path, 'utf8')
}

function assertIncludes(path, text, label = text) {
  assert.ok(read(path).includes(text), `${path} missing ${label}`)
}

assertIncludes('electron/main/db/migrations.ts', "schema_version', '8", 'schema version 8 migration')
assertIncludes('electron/main/db/migrations.ts', "schema_version', '9", 'schema version 9 migration')
assertIncludes('electron/main/db/migrations.ts', "schema_version', '11", 'schema version 11 migration')
assertIncludes('electron/main/db/migrations.ts', "schema_version', '12", 'schema version 12 migration')
assertIncludes('electron/main/db/schema.ts', 'is_favorite INTEGER NOT NULL DEFAULT 0')
assertIncludes('electron/main/db/schema.ts', 'task_id TEXT')
assertIncludes('electron/main/db/schema.ts', 'CREATE TABLE IF NOT EXISTS project_tasks')
assertIncludes('electron/main/db/schema.ts', 'CREATE TABLE IF NOT EXISTS project_task_files')
assertIncludes('electron/main/db/schema.ts', 'CREATE TABLE IF NOT EXISTS project_agents')
assertIncludes('electron/main/db/schema.ts', 'CREATE TABLE IF NOT EXISTS agent_workflow_runs')
assertIncludes('electron/main/db/schema.ts', 'project_type TEXT NOT NULL DEFAULT')
assertIncludes('electron/main/db/schema.ts', 'PRIMARY KEY (project_id, key)')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:getDashboard')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:saveTask')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:scanProfile')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', "from '../services/projectProfileScanner.js'")
assertIncludes('electron/main/services/projectProfileScanner.ts', 'scanProjectProfile')
assertIncludes('electron/main/services/projectProfileScanner.ts', 'package.json')
assertIncludes('electron/main/services/projectProfileScanner.ts', 'pom.xml')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:attachTaskFile')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:listAgents')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:createAgentWorkflowPlan')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:listKnowledge')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:search')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', 'projects:saveKnowledge')
assertIncludes('electron/main/db/repositories/projectKnowledgeRepository.ts', 'listProjectKnowledgeFromDb')
assertIncludes('electron/main/db/repositories/projectKnowledgeRepository.ts', 'saveProjectKnowledgeToDb')
assertIncludes('electron/main/db/repositories/projectKnowledgeRepository.ts', 'searchProjectKnowledgeFromDb')
assertIncludes('electron/main/db/repositories/projectKnowledgeRepository.ts', 'FROM project_tasks')
assertIncludes('electron/main/db/repositories/projectKnowledgeRepository.ts', 'FROM ai_history')
assertIncludes('electron/main/db/repositories/projectKnowledgeRepository.ts', 'FROM api_saved_requests')
assertIncludes('electron/main/ipc/registerSettingsIpc.ts', 'listProjectTasks({ projectId })')
assertIncludes('electron/main/ipc/registerSettingsIpc.ts', 'listProjectKnowledge({ projectId })')
assertIncludes('electron/main/ipc/registerSettingsIpc.ts', 'taskCount:')
assertIncludes('electron/main/ipc/registerSettingsIpc.ts', 'knowledgeCount:')
assertIncludes('electron/main/ipc/registerSettingsIpc.ts', 'taskIdMap')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', 'packagePreview.value.taskCount')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', 'packagePreview.value.knowledgeCount')
assertIncludes('README.md', 'v0.2.0 项目管理开发快照')
assertIncludes('README.md', '项目总览与任务')
assertIncludes('README.md', 'Agent工作站')
assertIncludes('README.md', '项目知识库')
assertIncludes('README.md', '项目内统一搜索')
assertIncludes('README.md', '项目数据包` 已覆盖项目资料、项目任务、项目知识库、AI 历史和 API 请求集合')
assertIncludes('docs/release-notes.md', 'v0.2.0 项目管理开发快照')
assertIncludes('docs/release-notes.md', 'Agent工作站')
assertIncludes('docs/release-notes.md', '项目知识库新增项目内统一搜索')
assertIncludes(
  'docs/release-notes.md',
  '项目数据包覆盖范围扩展为项目资料、项目任务、项目知识库、AI 历史和 API 请求集合'
)
assertIncludes('docs/release-checklist.md', '项目数据包覆盖项目资料、任务、知识条目、AI 历史和 API 请求')
assertIncludes('docs/release-checklist.md', 'Agent 工作站可维护项目级 Agent')
assertIncludes('docs/release-checklist.md', '项目知识库统一搜索结果限定在当前项目')
assertIncludes('docs/release-checklist.md', '任务 ID 会重建')
assertIncludes('electron/main/ipc/registerProjectsIpc.ts', "from '../services/projectTaskFileImporter.js'")
assertIncludes('electron/main/services/projectTaskFileImporter.ts', '5 * 1024 * 1024')
assertIncludes('electron/main/services/projectTaskFileImporter.ts', 'taskFileExtensions')
assertIncludes('electron/main/services/projectTaskFileImporter.ts', 'convertDocumentToMarkdown')
assertIncludes('electron/main/services/projectTaskFileImporter.ts', 'convertDocxToMarkdown')
assertIncludes('electron/main/services/projectTaskFileImporter.ts', 'convertXlsxToMarkdown')
assertIncludes('electron/main/services/projectTaskFileImporter.ts', 'convertPdfToMarkdown')
assertIncludes('electron/main/services/projectTaskFileImporter.ts', "'doc'")
assertIncludes('electron/main/services/projectTaskFileImporter.ts', "'xls'")
assertIncludes('electron/main/services/projectTaskFileImporter.ts', "'pdf'")
assertIncludes('electron/main/services/projectTaskFileImporter.ts', "'docx'")
assertIncludes('electron/main/services/projectTaskFileImporter.ts', "'xlsx'")
assertIncludes('electron/main/ipc/registerAiIpc.ts', 'taskId')
assertIncludes('electron/main/ipc/registerSettingsIpc.ts', 'details.push')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', '最近导入明细')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', '项目类型')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', '自动补全')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', '覆盖补全')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', 'mergeProjectProfileDraft(draft, overwrite)')
assertIncludes('src/renderer/views/ProjectWorkspace.vue', 'scanProfile')
assertIncludes('src/renderer/stores/projectContext.ts', 'currentProjectId')
assertIncludes('src/renderer/stores/projectContext.ts', 'loadProjectContext')
assertIncludes('src/renderer/views/ProjectDashboard.vue', 'loadProjectContext')
assertIncludes('src/renderer/views/ProjectTasks.vue', 'loadProjectContext')
assertIncludes('src/renderer/views/AiGenerate.vue', 'loadProjectContext')
assertIncludes('src/renderer/views/CodeReview.vue', 'loadProjectContext')
assertIncludes('src/renderer/views/ApiTester.vue', 'loadProjectContext')
assertIncludes('src/renderer/views/ApiTester.vue', 'selectedProjectTaskId')
assertIncludes('src/renderer/views/ApiTester.vue', 'taskId: selectedProjectTaskId.value || undefined')
assertIncludes('src/renderer/views/ApiTester.vue', "sourceType: selectedProjectTaskId.value ? 'task' : 'api_response'")
assertIncludes('src/renderer/views/GitAssistant.vue', 'loadProjectContext')
assertIncludes('src/renderer/views/AiHistoryCenter.vue', 'loadProjectContext')
assertIncludes('src/renderer/views/ProjectDashboard.vue', '项目总览')
assertIncludes('src/renderer/views/ProjectTasks.vue', '项目任务')
assertIncludes('src/renderer/views/ProjectTasks.vue', '关联 AI 输出')
assertIncludes('src/renderer/views/ProjectTasks.vue', '任务文件')
assertIncludes('src/renderer/views/ProjectAgents.vue', 'Agent 工作站')
assertIncludes('src/renderer/views/ProjectAgents.vue', '发送到 AI 开发')
assertIncludes('src/renderer/views/ProjectKnowledge.vue', '项目知识库')
assertIncludes('src/renderer/views/ProjectKnowledge.vue', 'saveKnowledge')
assertIncludes('src/renderer/views/ProjectKnowledge.vue', '项目内统一搜索')
assertIncludes('src/renderer/views/ProjectKnowledge.vue', 'searchResults')
assertIncludes('src/renderer/routes.ts', '/project-knowledge')
assertIncludes('src/renderer/routes.ts', '/project-agents')
assertIncludes('src/renderer/App.vue', '/project-knowledge')
assertIncludes('src/renderer/App.vue', '/project-agents')
assertIncludes('electron/main/services/ai.ts', '疑似乱码')
assertIncludes('src/renderer/views/AiGenerate.vue', '载入任务上下文')
assertIncludes('src/renderer/views/AiGenerate.vue', '重复异常字符')
assertIncludes('src/renderer/views/AiHistoryCenter.vue', '项目任务')
assertIncludes('src/renderer/views/AiHistoryCenter.vue', 'createKnowledgeFromSelected')
assertIncludes('src/renderer/views/AiHistoryCenter.vue', '沉淀知识')
assertIncludes('src/renderer/views/CodeReview.vue', '代码审查')
assertIncludes('src/renderer/routes.ts', '/code-review')
assertIncludes('src/renderer/routes.ts', '/dashboard')
assertIncludes('src/renderer/routes.ts', '/project-tasks')
assertIncludes('src/renderer/views/AiExplain.vue', 'loadContextFile')
assertIncludes('src/renderer/views/AiGenerate.vue', 'loadContextFile')
assertIncludes('src/renderer/views/GitAssistant.vue', 'reviewBeforeCommit')
assertIncludes('src/renderer/views/SettingsView.vue', '保存项目默认模板')
assertIncludes('src/renderer/App.vue', 'handleShortcut')
assertIncludes('src/renderer/styles.css', '@media (max-width: 980px)')
assertIncludes('docs/phase3-plan.md', '已支持 AI 上下文文件导入')
assertIncludes('docs/phase3-plan.md', '已支持提交前 AI 审查 diff')
assertIncludes('docs/phase3-plan.md', '已支持多模型平台配置')
assertIncludes('docs/phase3-plan.md', '已支持相对路径接口统一保留 `{{baseUrl}}` 前缀')
assertIncludes('src/renderer/views/ApiTester.vue', 'withBaseUrlPlaceholder')
assertIncludes('src/renderer/views/ApiTester.vue', 'savedRequestGroups')
assertIncludes('src/renderer/views/SettingsView.vue', 'providerOptions')
assertIncludes('electron/main/services/settings.ts', 'writeEnvValues')
assert.ok(!read('.env.example').includes('_MODEL='), '.env.example should not define model env variables')

assert.ok(existsSync('scripts/verify-build.mjs'), 'build verification script missing')

console.log('phase3 verification checks passed')
